In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

path = "/content/drive/MyDrive/AI-Personal-Finance-Management/ml/datasets/raw/Personal_Finance_Dataset.csv"

print(os.path.exists(path))

True

In [ ]:
import pandas as pd

df = pd.read_csv(path)

df.head()

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1500
Columns: 5

In [ ]:
df.columns

Index(['Date', 'Transaction Description', 'Category', 'Amount', 'Type'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     1500 non-null   object
 1   Transaction Description  1500 non-null   object
 2   Category                 1500 non-null   object
 3   Amount                   1500 non-null   float64
 4   Type                     1500 non-null   object
dtypes: float64(1), object(4)
memory usage: 58.7+ KB

In [ ]:
df.head(10)

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense
5,2020-01-14,Benefit suggest page southern.,Shopping,448.68,Expense
6,2020-01-18,By two bad fall pick.,Food & Drink,1520.03,Expense
7,2020-01-19,Court attorney product significant world.,Other,3287.00,Income
8,2020-01-21,Herself law.,Entertainment,1914.85,Expense
9,2020-01-25,Have decide environment.,Rent,766.06,Expense

In [ ]:
print(df.isnull().sum())

Date                       0
Transaction Description    0
Category                   0
Amount                     0
Type                       0
dtype: int64

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
df.describe(include="all")

,Date,Transaction Description,Category,Amount,Type
count,1500,1500,1500,1500.000000,1500
unique,1025,1500,10,NaN,2
top,2023-01-24,Pressure activity defense detail.,Rent,NaN,Expense
freq,6,1,165,NaN,1222
mean,NaN,NaN,NaN,1307.520913,NaN
std,NaN,NaN,NaN,982.283361,NaN
min,NaN,NaN,NaN,14.370000,NaN
25%,NaN,NaN,NaN,629.340000,NaN
50%,NaN,NaN,NaN,1156.285000,NaN
75%,NaN,NaN,NaN,1712.932500,NaN
max,NaN,NaN,NaN,4996.000000,NaN

In [ ]:
print("Transaction Type Counts:")
print(df["Type"].value_counts())

print("\nCategory Counts:")
print(df["Category"].value_counts())

Transaction Type Counts:
Type
Expense    1222
Income      278
Name: count, dtype: int64

Category Counts:
Category
Rent                165
Travel              160
Utilities           157
Health & Fitness    152
Shopping            150
Food & Drink        149
Salary              146
Entertainment       143
Investment          142
Other               136
Name: count, dtype: int64

In [ ]:
print("First date:", df["Date"].min())
print("Last date:", df["Date"].max())

print("\nNumber of unique dates:", df["Date"].nunique())

First date: 2020-01-02
Last date: 2024-12-29

Number of unique dates: 1025

In [ ]:
# Check whether all dates are valid

temp_dates = pd.to_datetime(df["Date"], errors="coerce")

print("Invalid dates:", temp_dates.isna().sum())

print("\nDate data type after conversion:")
print(temp_dates.dtype)

print("\nFirst 5 converted dates:")
print(temp_dates.head())

Invalid dates: 0

Date data type after conversion:
datetime64[ns]

First 5 converted dates:
0   2020-01-02
1   2020-01-02
2   2020-01-04
3   2020-01-05
4   2020-01-13
Name: Date, dtype: datetime64[ns]

In [ ]:
print("Overall Amount Statistics:")
print(df["Amount"].describe())

print("\nExpense Amount Statistics:")
print(df[df["Type"] == "Expense"]["Amount"].describe())

print("\nIncome Amount Statistics:")
print(df[df["Type"] == "Income"]["Amount"].describe())

Overall Amount Statistics:
count    1500.000000
mean     1307.520913
std       982.283361
min        14.370000
25%       629.340000
50%      1156.285000
75%      1712.932500
max      4996.000000
Name: Amount, dtype: float64

Expense Amount Statistics:
count    1222.000000
mean     1004.250712
std       571.536986
min        14.370000
25%       516.802500
50%       992.855000
75%      1484.937500
max      1999.820000
Name: Amount, dtype: float64

Income Amount Statistics:
count     278.000000
mean     2640.600719
std      1261.890414
min       500.000000
25%      1531.750000
50%      2655.000000
75%      3609.250000
max      4996.000000
Name: Amount, dtype: float64

In [ ]:
# Create a separate working copy
data = df.copy()

print("Original df shape:", df.shape)
print("Working data shape:", data.shape)

Original df shape: (1500, 5)
Working data shape: (1500, 5)

In [ ]:
# Convert Date column to datetime
data["Date"] = pd.to_datetime(data["Date"])

print("Date data type:", data["Date"].dtype)
print("Missing dates:", data["Date"].isna().sum())

Date data type: datetime64[ns]
Missing dates: 0

In [ ]:
print("Transaction Types:")
print(data["Type"].value_counts())

Transaction Types:
Type
Expense    1222
Income      278
Name: count, dtype: int64

In [ ]:
print("Categories:")
print(data["Category"].value_counts())

Categories:
Category
Rent                165
Travel              160
Utilities           157
Health & Fitness    152
Shopping            150
Food & Drink        149
Salary              146
Entertainment       143
Investment          142
Other               136
Name: count, dtype: int64

In [ ]:
# Create a separate dataset containing only expenses
expenses = data[data["Type"] == "Expense"].copy()

print("Expense dataset shape:", expenses.shape)
print("\nTransaction types:")
print(expenses["Type"].value_counts())

Expense dataset shape: (1222, 5)

Transaction types:
Type
Expense    1222
Name: count, dtype: int64

In [ ]:
# Create time-based features
expenses["Year"] = expenses["Date"].dt.year
expenses["Month"] = expenses["Date"].dt.month
expenses["Month_Name"] = expenses["Date"].dt.month_name()
expenses["Year_Month"] = expenses["Date"].dt.to_period("M")

print(expenses[["Date", "Year", "Month", "Month_Name", "Year_Month"]].head())

        Date  Year  Month Month_Name Year_Month
0 2020-01-02  2020      1    January    2020-01
1 2020-01-02  2020      1    January    2020-01
2 2020-01-04  2020      1    January    2020-01
4 2020-01-13  2020      1    January    2020-01
5 2020-01-14  2020      1    January    2020-01

In [ ]:
print("Number of months:", expenses["Year_Month"].nunique())

print("\nFirst month:", expenses["Year_Month"].min())
print("Last month:", expenses["Year_Month"].max())

Number of months: 60

First month: 2020-01
Last month: 2024-12

In [ ]:
# Monthly expense aggregation

monthly_expenses = expenses.groupby("Year_Month").agg(
    Total_Expense=("Amount", "sum"),
    Transaction_Count=("Amount", "count"),
    Average_Expense=("Amount", "mean"),
    Max_Expense=("Amount", "max"),
    Min_Expense=("Amount", "min")
).reset_index()

print("Monthly dataset shape:", monthly_expenses.shape)

print("\nFirst 5 months:")
print(monthly_expenses.head())

Monthly dataset shape: (60, 6)

First 5 months:
  Year_Month  Total_Expense  Transaction_Count  Average_Expense  Max_Expense  \
0    2020-01       17138.25                 15      1142.550000      1914.85
1    2020-02       17108.41                 15      1140.560667      1979.15
2    2020-03       13581.81                 15       905.454000      1956.19
3    2020-04       16233.05                 13      1248.696154      1938.30
4    2020-05       16846.13                 21       802.196667      1878.47

   Min_Expense
0       166.81
1       294.31
2       144.13
3       340.96
4        28.54

In [ ]:
print("\nLast 5 months:")
print(monthly_expenses.tail())

print("\nMissing values:")
print(monthly_expenses.isnull().sum())

print("\nData types:")
print(monthly_expenses.dtypes)

Last 5 months:
   Year_Month  Total_Expense  Transaction_Count  Average_Expense  Max_Expense  \
55    2024-08       22933.69                 20      1146.684500      1891.97
56    2024-09       19383.94                 20       969.197000      1879.91
57    2024-10       22984.21                 22      1044.736818      1958.95
58    2024-11       23565.96                 26       906.383077      1950.21
59    2024-12       10938.92                 15       729.261333      1949.45

    Min_Expense
55       397.55
56       117.75
57       167.43
58        62.47
59        39.30

Missing values:
Year_Month           0
Total_Expense        0
Transaction_Count    0
Average_Expense      0
Max_Expense          0
Min_Expense          0
dtype: int64

Data types:
Year_Month           period[M]
Total_Expense          float64
Transaction_Count        int64
Average_Expense        float64
Max_Expense            float64
Min_Expense            float64
dtype: object

In [ ]:
# Create numerical time features

monthly_expenses["Year"] = monthly_expenses["Year_Month"].dt.year
monthly_expenses["Month"] = monthly_expenses["Year_Month"].dt.month

print(monthly_expenses.head())
print("\nData types:")
print(monthly_expenses.dtypes)

  Year_Month  Total_Expense  Transaction_Count  Average_Expense  Max_Expense  \
0    2020-01       17138.25                 15      1142.550000      1914.85
1    2020-02       17108.41                 15      1140.560667      1979.15
2    2020-03       13581.81                 15       905.454000      1956.19
3    2020-04       16233.05                 13      1248.696154      1938.30
4    2020-05       16846.13                 21       802.196667      1878.47

   Min_Expense  Year  Month
0       166.81  2020      1
1       294.31  2020      2
2       144.13  2020      3
3       340.96  2020      4
4        28.54  2020      5

Data types:
Year_Month           period[M]
Total_Expense          float64
Transaction_Count        int64
Average_Expense        float64
Max_Expense            float64
Min_Expense            float64
Year                     int64
Month                    int64
dtype: object

In [ ]:
# Create lag features using only previous months

monthly_expenses["Previous_Month_Expense"] = (
    monthly_expenses["Total_Expense"].shift(1)
)

monthly_expenses["Expense_2_Months_Ago"] = (
    monthly_expenses["Total_Expense"].shift(2)
)

monthly_expenses["Expense_3_Months_Ago"] = (
    monthly_expenses["Total_Expense"].shift(3)
)

monthly_expenses["Previous_Transaction_Count"] = (
    monthly_expenses["Transaction_Count"].shift(1)
)

# 3-month rolling average using previous months only
monthly_expenses["Three_Month_Avg_Expense"] = (
    monthly_expenses["Total_Expense"].shift(1).rolling(window=3).mean()
)

print(monthly_expenses.head(7))

  Year_Month  Total_Expense  Transaction_Count  Average_Expense  Max_Expense  \
0    2020-01       17138.25                 15      1142.550000      1914.85
1    2020-02       17108.41                 15      1140.560667      1979.15
2    2020-03       13581.81                 15       905.454000      1956.19
3    2020-04       16233.05                 13      1248.696154      1938.30
4    2020-05       16846.13                 21       802.196667      1878.47
5    2020-06       20680.72                 22       940.032727      1947.94
6    2020-07       24026.27                 22      1092.103182      1900.58

   Min_Expense  Year  Month  Previous_Month_Expense  Expense_2_Months_Ago  \
0       166.81  2020      1                     NaN                   NaN
1       294.31  2020      2                17138.25                   NaN
2       144.13  2020      3                17108.41              17138.25
3       340.96  2020      4                13581.81              17108.41
4        28.54  2020      5                16233.05              13581.81
5        86.13  2020      6                16846.13              16233.05
6       109.93  2020      7                20680.72              16846.13

   Expense_3_Months_Ago  Previous_Transaction_Count  Three_Month_Avg_Expense
0                   NaN                         NaN                      NaN
1                   NaN                        15.0                      NaN
2                   NaN                        15.0                      NaN
3              17138.25                        15.0             15942.823333
4              17108.41                        13.0             15641.090000
5              13581.81                        21.0             15553.663333
6              16233.05                        22.0             17919.966667

In [ ]:
# Create the dataset for machine learning
# We need 3 months of previous data for our lag features

model_data = monthly_expenses.dropna().copy()

print("Original monthly rows:", len(monthly_expenses))
print("Rows available for ML:", len(model_data))

print("\nMissing values:")
print(model_data.isnull().sum())

Original monthly rows: 60
Rows available for ML: 57

Missing values:
Year_Month                    0
Total_Expense                 0
Transaction_Count             0
Average_Expense               0
Max_Expense                   0
Min_Expense                   0
Year                          0
Month                         0
Previous_Month_Expense        0
Expense_2_Months_Ago          0
Expense_3_Months_Ago          0
Previous_Transaction_Count    0
Three_Month_Avg_Expense       0
dtype: int64

In [ ]:
print(model_data.head())

print("\nShape:", model_data.shape)

  Year_Month  Total_Expense  Transaction_Count  Average_Expense  Max_Expense  \
3    2020-04       16233.05                 13      1248.696154      1938.30
4    2020-05       16846.13                 21       802.196667      1878.47
5    2020-06       20680.72                 22       940.032727      1947.94
6    2020-07       24026.27                 22      1092.103182      1900.58
7    2020-08       31386.80                 25      1255.472000      1999.82

   Min_Expense  Year  Month  Previous_Month_Expense  Expense_2_Months_Ago  \
3       340.96  2020      4                13581.81              17108.41
4        28.54  2020      5                16233.05              13581.81
5        86.13  2020      6                16846.13              16233.05
6       109.93  2020      7                20680.72              16846.13
7        67.76  2020      8                24026.27              20680.72

   Expense_3_Months_Ago  Previous_Transaction_Count  Three_Month_Avg_Expense
3              17138.25                        15.0             15942.823333
4              17108.41                        13.0             15641.090000
5              13581.81                        21.0             15553.663333
6              16233.05                        22.0             17919.966667
7              16846.13                        22.0             20517.706667

Shape: (57, 13)

In [ ]:
# Define features and target

features = [
    "Year",
    "Month",
    "Previous_Month_Expense",
    "Expense_2_Months_Ago",
    "Expense_3_Months_Ago",
    "Previous_Transaction_Count",
    "Three_Month_Avg_Expense"
]

X = model_data[features]
y = model_data["Total_Expense"]

print("Features (X) shape:", X.shape)
print("Target (y) shape:", y.shape)

print("\nFeatures:")
print(X.head())

print("\nTarget:")
print(y.head())

Features (X) shape: (57, 7)
Target (y) shape: (57,)

Features:
   Year  Month  Previous_Month_Expense  Expense_2_Months_Ago  \
3  2020      4                13581.81              17108.41
4  2020      5                16233.05              13581.81
5  2020      6                16846.13              16233.05
6  2020      7                20680.72              16846.13
7  2020      8                24026.27              20680.72

   Expense_3_Months_Ago  Previous_Transaction_Count  Three_Month_Avg_Expense
3              17138.25                        15.0             15942.823333
4              17108.41                        13.0             15641.090000
5              13581.81                        21.0             15553.663333
6              16233.05                        22.0             17919.966667
7              16846.13                        22.0             20517.706667

Target:
3    16233.05
4    16846.13
5    20680.72
6    24026.27
7    31386.80
Name: Total_Expense, dtype: float64

In [ ]:
# Time-based train-test split

split_index = int(len(model_data) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

print("Training data:")
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

print("\nTesting data:")
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

print("\nTraining period:")
print(model_data["Year_Month"].iloc[0], "to", model_data["Year_Month"].iloc[split_index - 1])

print("\nTesting period:")
print(model_data["Year_Month"].iloc[split_index], "to", model_data["Year_Month"].iloc[-1])

Training data:
X_train shape: (45, 7)
y_train shape: (45,)

Testing data:
X_test shape: (12, 7)
y_test shape: (12,)

Training period:
2020-04 to 2023-12

Testing period:
2024-01 to 2024-12

In [ ]:
# Save processed ML-ready dataset

processed_path = "/content/drive/MyDrive/AI-Personal-Finance-Management/ml/datasets/processed/monthly_expenses_ml_ready.csv"

model_data.to_csv(processed_path, index=False)

print("Processed dataset saved successfully!")
print("Path:", processed_path)
print("Shape:", model_data.shape)

Processed dataset saved successfully!
Path: /content/drive/MyDrive/AI-Personal-Finance-Management/ml/datasets/processed/monthly_expenses_ml_ready.csv
Shape: (57, 13)